export const environment = {
  production: false,
  oauthToken: "Bearer BQAfLfPFo1N1Kpg5kWjSLwRACmCzMw1j0f8ALOPOPcqXBbR4N4dBLiQudJgQl6LLHG7zHUsYjtSrepuQOcoD3A6YuHK7FvwSLdlkAlMNpGhhFDcIjmwu2K5KCYhBbbab1CbN4IjDc9adnH_CGXwjLg6Q6R13__vXNsiutegVLx4ztBZO"
};

